///////////////////////////////////////////////////////////
//  BouteilleV2.cs
//  Implementation of the Class Bouteille
//  Generated by Enterprise Architect
//  Created on:      06-févr.-2025 11:00:05
//  Original author: BHerault
///////////////////////////////////////////////////////////




namespace salutionBouteile {
	public class Bouteille {

		private double contenanceEnLitre;
		private double contenuEnLitre;
		private bool estOuvert;



		~Bouteille(){

		}

		public virtual void Dispose(){

		}

		public Bouteille(){

		}

		/// 
		/// <param name="contenanceEnLitre"></param>
		/// <param name="contenuEnLitre"></param>
		/// <param name="ouverte"></param>
		public Bouteille(double contenanceEnLitre, double contenuEnLitre, bool ouverte){

		}

		/// 
		/// <param name="bouteilleACopier"></param>
		public Bouteille(Bouteille bouteilleACopier){

		}

		public bool Ouvrir(){

			return false;
		}

		public bool Fermer(){

			return false;
		}

		public bool Vider(){

			return false;
		}

		/// 
		/// <param name="quantiteEnLitre"></param>
		public bool Vider(double quantiteEnLitre){

			return false;
		}

		public bool Remplir(){

			return false;
		}

		/// 
		/// <param name="quantiteEnLitre"></param>
		public bool Remplir(double quantiteEnLitre){

			return false;
		}

	}//end Bouteille

}//end namespace salutionBouteile